[package]
name = "mini-stat"
version = "0.4.0"
edition = "2021"

[features]
default = ["refcell", "sync"]
refcell = []
sync = []

[dependencies]
smallvec = { version = "1.13.2", features = ["const_generics"] }
